version: '3.8'

services:
  versade:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: versade
    ports:
      - "9373:9373"
    environment:
      - VERSADE_PORT=9373
      - VERSADE_LOG_LEVEL=INFO
      - VERSADE_CORS_ORIGINS=*
      - VERSADE_MAX_REQUEST_SIZE=1048576
      - VERSADE_RATE_LIMIT_REQUESTS=5
      - VERSADE_RATE_LIMIT_WINDOW=1
      - VERSADE_TIMEOUT=30.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9373/health"]
      interval: 30s
      timeout: 10s
      retries: 3
